name: Build and Test Bot
on: 
  [push]
jobs:

  build:
    name: Runs Tests
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get Dependencies
      run: |
        go get -v -t -d ./...

    - name: Runs Unit Tests
      run: |
       export DB="${{ secrets.DB }}"
       export DBUSER="${{ secrets.DBUSER }}"
       export DBHOST="${{ secrets.DBHOST }}"
       export DBPASSWD="${{ secrets.DBPASSWD }}"
       export DBPORT="${{ secrets.DBPORT }}"
       go test -run ''
